### ISSUE TITLE
Access denied exception

### ISSUE THREAD

**Issue by nvamshik** [awsdocs/elb-classic-load-balancers-user-guide#2]
We are trying to enable access logs for our classic Elastic loadbalancer and route those logs to one of our existing KMS encryption enabled S3 buckets. I have also added the following S3 bucket policy so that it grants permissions to ELB to write logs in that specified S3 bucket.

{
            "Action": "s3:PutObject",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*******/ServerLogs/*",
            "Principal": {
                "AWS": [
                    "127311923021"
                ]
            }
        }

But We are seeing an Access denied exception. Can you please let me know if it is using a specific role or am I doing something wrong? Please let me know.

**Comment by julieso** [comment]
Apologies for the delayed response. Did you solve the issue? One difference I see between this policy and the documentation is the Version field. The 2012-10-17 version is required in order to specify resource-level permissions.

**Comment by nvamshik** [comment]
No it was not solved yet. I have version field in place. Still I was not able to route the logs to KMS encryption enabled bucket. But was able to send the logs to a AES encryption enabled bucket.

**Comment by julieso** [comment]
Thanks for getting back to me. The docs for the Application Load Balancer say that we support SSE-S3; we do not support SSE-KMS. I'll update the documentation for the Classic Load Balancer.

**Comment by nvamshik** [comment]
Sure, Thank you! Is this the same case for sending VPC flowlogs to KMS encryption enabled S3 bucket? Please let me know. Thanks!

**Comment by julieso** [comment]
Really sorry that I missed this last comment. The docs for VPC flowlogs indicate support for SSE-KMS.
